// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY46qSTNoj4JS_GVUrLBXSYZpnK74GNo8',
    appId: '1:1061668468125:web:f7069844d862893a136b74',
    messagingSenderId: '1061668468125',
    projectId: 'pet-care-app-aa20e',
    authDomain: 'pet-care-app-aa20e.firebaseapp.com',
    storageBucket: 'pet-care-app-aa20e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSWCbC29mnzmnRpqVLaHF5XhVv-myMeoM',
    appId: '1:1061668468125:android:7c7f6ed2425d7882136b74',
    messagingSenderId: '1061668468125',
    projectId: 'pet-care-app-aa20e',
    storageBucket: 'pet-care-app-aa20e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALJwc2ZAkNlJ19NZ57hqDubx6p280jMq8',
    appId: '1:1061668468125:ios:2a4c1e0a095cf26a136b74',
    messagingSenderId: '1061668468125',
    projectId: 'pet-care-app-aa20e',
    storageBucket: 'pet-care-app-aa20e.firebasestorage.app',
    iosBundleId: 'com.example.habit_tail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALJwc2ZAkNlJ19NZ57hqDubx6p280jMq8',
    appId: '1:1061668468125:ios:2a4c1e0a095cf26a136b74',
    messagingSenderId: '1061668468125',
    projectId: 'pet-care-app-aa20e',
    storageBucket: 'pet-care-app-aa20e.firebasestorage.app',
    iosBundleId: 'com.example.habit_tail',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY46qSTNoj4JS_GVUrLBXSYZpnK74GNo8',
    appId: '1:1061668468125:web:060b1c747fd5936e136b74',
    messagingSenderId: '1061668468125',
    projectId: 'pet-care-app-aa20e',
    authDomain: 'pet-care-app-aa20e.firebaseapp.com',
    storageBucket: 'pet-care-app-aa20e.firebasestorage.app',
  );

}